[package]
name = "fixie-trie"
version = "0.1.1"
authors = ["Julian Squires <julian@cipht.net>"]
publish = false

[features]
i128 = []

[dependencies]

[dev-dependencies]
quickcheck = "0.4.1"
rand = "*"
qp-trie = "0.7.1"